# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QIcon
import  sys
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(345, 365)
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 150, 121, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 150, 71, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 60, 71, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 60, 121, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 100, 71, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 100, 121, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(160, 210, 81, 41))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 280, 181, 41))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(53, 280, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 220, 121, 21))
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_3.setText(_translate("Dialog", "时间间隔"))
        self.pushButton_4.setText(_translate("Dialog", "用户名"))
        self.pushButton_5.setText(_translate("Dialog", "密码"))
        self.pushButton.setText(_translate("Dialog", "自动联网"))
        self.label.setText(_translate("Dialog", "Not Working"))
        self.pushButton_2.setText(_translate("Dialog", "Check-Net"))
        self.lineEdit_5.setAlignment(Qt.AlignCenter)
        self.lineEdit_4.setAlignment(Qt.AlignCenter)
        self.lineEdit_3.setAlignment(Qt.AlignCenter)
        self.pushButton_6.setText(_translate("Dialog", "选择Chrome_driver"))
        pushbutton_list = [self.pushButton_3,self.pushButton_4,self.pushButton_5]
        for button in pushbutton_list:
            button.setStyleSheet('''QPushButton{border:none;color:black;padding-left:5px;
                                height:35px;
                                font-size:13px;
                                padding-right:10px;}''')
        Dialog.setWindowTitle("自动联网")
        # palette = QPalette()
        # palette.setBrush(QPalette.Background, QBrush(QPixmap("./images/python.jpg")))
        # win.setPalette(palette)
        self.label.setStyleSheet("QLabel{color:black;font-size:14px;font-weight:bold;font-family:Roman times;}")
        Dialog.setStyleSheet("#Dialog{border-image:url(./hdu2.jpg);}")
        self.pushButton_2.setStyleSheet("QPushButton{background:lightgray;border-radius:5px;font-family:Roman times;}QPushButton:hover{background:darkgray;}")
        self.pushButton_6.setStyleSheet(
            "QPushButton{background:lightgray;border-radius:5px;font-family:Roman times;}QPushButton:hover{background:darkgray;}")
        self.pushButton.setStyleSheet(
            "QPushButton{background:lightgray;border-radius:15px;font-family:Roman times;}QPushButton:hover{background:darkgray;}")
        self.label.setAlignment(Qt.AlignCenter)
        Dialog.setWindowIcon(QIcon('net.png'))  # 设置logo
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    widgets = QtWidgets.QMainWindow()
    ui = Ui_Dialog()
    ui.setupUi(widgets)
    widgets.show()
    sys.exit(app.exec_())